In [2]:
import numpy as np

Definindo um array

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

O array "a" é um numpy.ndarray de um tipo só 'int32'

In [5]:
a.dtype

dtype('int32')

In [6]:
a.ndim

1

In [7]:
a.size

3

In [8]:
b = np.array([[1.3, 3.4], [0.5, 4.2]])

In [9]:
b

array([[1.3, 3.4],
       [0.5, 4.2]])

In [11]:
b.dtype

dtype('float64')

In [12]:
b.ndim

2

In [13]:
b.size

4

In [14]:
b.shape

(2, 2)

In [15]:
b.itemsize

8

In [16]:
b.data

In [22]:
c = np.array([[1,2,3],[4,5,6]])

In [23]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
d = np.array(((1,2,3),(4,5,6)))

In [25]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
e = np.array([(1,2,3), [4,5,6], (7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
g = np.array([['a', 'b'], ['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [32]:
g.dtype

dtype('<U1')

In [30]:
g.dtype.name

'str32'

In [36]:
f = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [37]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [42]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [43]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
np.random.random(3)

array([0.90058108, 0.07194359, 0.76012667])

In [49]:
np.random.random((3,3))

array([[0.65332303, 0.41845405, 0.94463289],
       [0.63107616, 0.48039367, 0.47162746],
       [0.27053946, 0.30505899, 0.52075563]])

In [50]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [51]:
a + 4

array([4, 5, 6, 7])

In [52]:
a * 2

array([0, 2, 4, 6])

In [54]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [55]:
a + b

array([ 4,  6,  8, 10])

In [56]:
a - b

array([-4, -4, -4, -4])

In [57]:
a * b

array([ 0,  5, 12, 21])

In [59]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [60]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [63]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [67]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [68]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [70]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [71]:
a += 1

In [72]:
a

array([1, 2, 3, 4])

In [73]:
a -= 1

In [74]:
a

array([0, 1, 2, 3])

In [75]:
a += 4

In [76]:
a

array([4, 5, 6, 7])

In [77]:
a *= 5

In [78]:
a

array([20, 25, 30, 35])

## Funçoes universais ufunc

In [80]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [81]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [82]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [83]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Funções de agregração

In [84]:
a = np.array([3.3, 1.2, 4.5, 0.6])

In [86]:
a.sum()

9.6

In [87]:
a.max()

4.5

In [88]:
a.min()

0.6

In [89]:
a.mean()

2.4

In [90]:
a.std()

1.5732132722552272

## Indexando, fatiando e iterando

In [4]:
#indexanndo
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [5]:
a[4]

14

In [6]:
a[-1]

15

In [7]:
a[-6]

10

In [8]:
a[[1, 3, 4]]

array([11, 13, 14])